### ISSUE TITLE
Poor parameter names in alert() method

### ISSUE THREAD

**Issue by jbrucker** [PitchapaSaelim/refactoring#1]
In a List, the add method is: `add(item)` not `add(addItem)`.

In a TextBox, the method to set the text is `textbox.setText(text)` 
not `textbox.setText(setText)`.

Putting "set" on parameter names is pointless.
```
public void alert(Alert.AlertType setAlertType, String setTitle, String setHeaderText, String setContentText) 
```
should be
```
public void alert(Alert.AlertType slertType, String title, String header, String message) {
```

**Comment by PitchapaSaelim** [comment]
Sorry for the mistake, I fixed it. Thank you.
